### ISSUE TITLE
New Shortcodes

### ISSUE THREAD

**Issue by dacog** [getnikola/shortcodes#3]
Hi, 

I created some shortcodes for my site based on the default Nikola Theme (bootstrap 4 and Jinja2).

One is a shortcode to add something like a series-button

` {{% series_buttons previous_url="/previous-article" previous_text="Previous Article Title" next_url="/next-article" next_text="Next Article Title" %}}`

and looks like this:

![Screenshot_20231208_161857](https://github.com/getnikola/shortcodes/assets/557703/a7de260a-fc14-4c3a-868d-a8511c1c4b28)

and the other one is a shortcode to add a note box with different icons. 

` {{% notebox type="book" text="This is a book notebox"  %}}`

This looks like this:

![Screenshot_20231208_161735](https://github.com/getnikola/shortcodes/assets/557703/dc9ab2cc-8c4c-458e-b7d2-4be584421712)

Would it be ok to add them to the repo or are they to specific?

Best, 

Diego

**Comment by Kwpolska** [comment]
Those shortcodes seem useful to more than one person — feel free to submit a pull request :)

**Comment by dacog** [comment]
Hi @Kwpolska 

Great! Here is the Pull Request https://github.com/getnikola/shortcodes/pull/4

If there is anything I should change, please do tell me. I tried following the format of the other entries.
